"""add image_url to posts

Revision ID: 37aa50a9f48b
Revises: 35305c4f1fdd
Create Date: 2026-02-22 15:56:52.838067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37aa50a9f48b"
down_revision: Union[str, Sequence[str], None] = "35305c4f1fdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "image_url")
    # ### end Alembic commands ###
