"""update users model

Revision ID: 87a77b869274
Revises: initial
Create Date: 2026-02-24 22:50:16.089569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87a77b869274'
down_revision: Union[str, Sequence[str], None] = 'initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('likes', 'post_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('posts', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('users', sa.Column('public_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('private_key', sa.Text(), nullable=True))
    op.drop_column('users', 'rsa_private_key')
    op.drop_column('users', 'rsa_public_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rsa_public_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('rsa_private_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'private_key')
    op.drop_column('users', 'public_key')
    op.alter_column('posts', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('likes', 'post_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('likes', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
