"""add columns for federation

Revision ID: c2422bc78755
Revises: e90a5a9bb0a1
Create Date: 2026-03-03 19:05:11.022194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2422bc78755'
down_revision: Union[str, Sequence[str], None] = 'e90a5a9bb0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('local_user_id', sa.String(), nullable=True))
    op.add_column('connections', sa.Column('target_local_user_id', sa.String(), nullable=True))
    op.add_column('connections', sa.Column('remote_actor_url', sa.String(), nullable=True))
    op.add_column('connections', sa.Column('remote_inbox_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('connections_requester_id_fkey'), 'connections', type_='foreignkey')
    op.create_foreign_key(None, 'connections', 'users', ['target_local_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connections', 'users', ['local_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('connections', 'target_actor')
    op.drop_column('connections', 'requester_id')
    op.alter_column('likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('password_resets_user_id_fkey'), 'password_resets', type_='foreignkey')
    op.create_foreign_key(None, 'password_resets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('posts', sa.Column('visibility', sa.String(), nullable=True))

    op.alter_column('posts', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('public_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('private_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'private_key')
    op.drop_column('users', 'public_key')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_user_id_fkey'), 'posts', 'users', ['user_id'], ['id'])
    op.alter_column('posts', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('posts', 'visibility')
    op.drop_constraint(None, 'password_resets', type_='foreignkey')
    op.create_foreign_key(op.f('password_resets_user_id_fkey'), 'password_resets', 'users', ['user_id'], ['id'])
    op.alter_column('likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('connections', sa.Column('requester_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('connections', sa.Column('target_actor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.create_foreign_key(op.f('connections_requester_id_fkey'), 'connections', 'users', ['requester_id'], ['id'])
    op.drop_column('connections', 'remote_inbox_url')
    op.drop_column('connections', 'remote_actor_url')
    op.drop_column('connections', 'target_local_user_id')
    op.drop_column('connections', 'local_user_id')
    # ### end Alembic commands ###
