"""add visibility feature

Revision ID: e90a5a9bb0a1
Revises: 1d0be69de1df
Create Date: 2026-03-02 23:08:42.215351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90a5a9bb0a1'
down_revision: Union[str, Sequence[str], None] = '1d0be69de1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # 1️⃣ Add column with temporary nullable=True
    op.add_column(
        'posts',
        sa.Column('visibility', sa.String(), nullable=True)
    )

    # 2️⃣ Backfill existing rows
    op.execute("UPDATE posts SET visibility = 'public'")

    # 3️⃣ Make it non-nullable
    op.alter_column(
        'posts',
        'visibility',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('posts', 'visibility')

    # ### end Alembic commands ###
