"""add_author_avatar_url_to_posts

Revision ID: f44bde9d40a8
Revises: 446e3782e7bc
Create Date: 2026-02-26 14:36:08.070641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44bde9d40a8'
down_revision: Union[str, Sequence[str], None] = '446e3782e7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author_avatar_url')
    # ### end Alembic commands ###
